# Generated by Django 4.1 on 2022-08-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user_id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
