# Generated by Django 4.1 on 2022-08-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useranime_userlist_alter_user_options_user_anime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='images',
            field=models.JSONField(blank=True, default=dict, verbose_name='Images'),
        ),
    ]
