# Generated by Django 4.1 on 2022-08-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_remove_animelist_anime_id_remove_animelist_list_id_and_more'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='anime',
            field=models.ManyToManyField(to='animes.anime'),
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
