# Generated by Django 4.1 on 2022-08-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('users', '0003_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('images', models.JSONField(default=dict, verbose_name='Images')),
                ('name', models.CharField(max_length=255)),
                ('other_name', models.CharField(max_length=255)),
                ('released', models.DateTimeField()),
                ('episodes', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('broadcast_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('season_year', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAnime',
            fields=[
                ('useranime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('watching', 'Watching'), ('paused', 'Paused'), ('finished', 'Finished')], max_length=8)),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animes.anime')),
                ('genre_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genres.genre')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='broadcast_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animes.broadcast'),
        ),
        migrations.AddField(
            model_name='anime',
            name='season_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animes.season'),
        ),
    ]
