# Generated by Django 4.1 on 2022-08-25 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_remove_animelist_anime_id_remove_animelist_list_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['name'], 'verbose_name': 'Anime', 'verbose_name_plural': 'Animes'},
        ),
        migrations.RemoveField(
            model_name='season',
            name='description',
        ),
        migrations.AddField(
            model_name='season',
            name='season',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
