# Generated by Django 4.1 on 2022-08-31 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamingplatforms', '0002_delete_animestreamingplatform'),
        ('animes', '0004_alter_anime_options_remove_season_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeStreamingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_url', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='streaming_platform',
            field=models.ManyToManyField(related_name='anime_id', through='animes.AnimeStreamingPlatform', to='streamingplatforms.streamingplatform'),
        ),
        migrations.AddField(
            model_name='animestreamingplatform',
            name='anime_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime'),
        ),
        migrations.AddField(
            model_name='animestreamingplatform',
            name='streamingplatform_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamingplatforms.streamingplatform'),
        ),
    ]
