# Generated by Django 4.1 on 2022-08-23 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingPlatform',
            fields=[
                ('streamingplatform_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('urls', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeStreamingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_url', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
                ('streamingplatform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamingplatforms.streamingplatform')),
            ],
        ),
    ]
