# Generated by Django 4.1 on 2022-08-31 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamingplatforms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimeStreamingPlatform',
        ),
    ]
